### ISSUE TITLE
i cant see the problem when after i use this please help

### ISSUE THREAD

**Issue by shoko1** [kodie/gameranger-account-switcher#2]
i have been use it but i cant use gameranger anymore no matter what i cant even port and when i did it not working and not log in to game ranger  and even my game does not connect to the onilne 
and evenmore it have been doing some werid spouicis on my net i m tring to get in my servers and router but can get in please just help me figure it out 

i dont blame any1 just if you can help me what can possibly go wrong because i cant fiugre by myslef 
can it set some new setting that idont know of ?
i have been using it back and forth  to get in into accounts in short time period as you said 
please just help me fuigure it out

**Comment by kodie** [comment]
@shoko1 As I told you in Issue #1, I cannot provide any further assistance on the issue as it is not related to this application and this is not a GameRanger support forum. I honestly have no idea how to solve the issue you are having. You need to contact someone from GameRanger, not me.

**Comment by shoko1** [comment]
but i cant even log in to gameranger to talk on the forum ...
please just tell how this work does it make a new proxy or somting i can
delete ?

2017-09-13 17:28 GMT+03:00 Kodie Grantham <notifications@github.com>:

**Comment by kodie** [comment]
You should try to contact GameRanger directly here: https://www.gameranger.com/support/game/

As I also told you in Issue #1, this application simply moves/renames your GameRanger Settings file, nothing more, nothing less.
