### ISSUE TITLE
Where are Account details saved?

### ISSUE THREAD

**Issue by danutzzzzz** [kodie/gameranger-account-switcher#3]
Hi, as per subject, Where are account details saved for the GRAS app?

**Comment by kodie** [comment]
@daNutzzzzz GameRanger stores your account details in `C:\users\user\appdata\Roaming\GameRanger\GameRanger\GameRanger Prefs\Settings`.

GRAS simply moves and renames that file to `C:\users\user\appdata\Roaming\GameRanger\GameRanger\AccountSwitcher\Accounts\{Nickname you gave the account}`.

So when you switch to a different account it simply swaps out those two files.
